name: Core Checks
on:
  workflow_dispatch:
  pull_request:
    paths: 
      - .github/workflows/core.yml
      - CMSIS/Core/Include/**/*
      - CMSIS/Core/Source/**/*
      - CMSIS/Core/Test/**/*
  push:
    branches: [main]
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lit:
    runs-on: ubuntu-22.04

    env:
      ARM_UBL_ACTIVATION_CODE: ${{ secrets.ARM_UBL_ACTIVATION_CODE }}
      IAR_LMS_BEARER_TOKEN: ${{ secrets.IAR_LMS_BEARER_TOKEN }}

    steps:
      - uses: actions/checkout@v5
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'    
          cache: 'pip'

      - name: Python requirements
        run: |
          pip install -r ./CMSIS/Core/Test/requirements.txt

      - name: Install LLVM dependencies and tools
        working-directory: /home/runner
        run: |
          sudo apt-get update
          sudo apt-get install libtinfo5 llvm-15-tools
          sudo ln -s /usr/bin/FileCheck-15 /usr/bin/FileCheck

      - name: Install IAR Toolchain
        working-directory: /home/runner
        run: |
          curl -sLO https://github.com/iarsystems/arm/releases/download/9.70.1/cxarm-9.70.1-linux-x86_64-base.tar.bz2
          tar -xjf cxarm-9.70.1-linux-x86_64-base.tar.bz2
          echo "PATH=$PATH:$(pwd)/cxarm-9.70.1/arm/bin" >> $GITHUB_ENV
          echo "IAR_TOOLCHAIN_9_70_1=$(pwd)/cxarm-9.70.1/arm/bin" >> $GITHUB_ENV
      
      - name: Activate vcpkg environment
        uses: ARM-software/cmsis-actions/vcpkg@v1
        with:
          config: ./CMSIS/Core/Test/vcpkg-configuration.json

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1
        with:
          code: "${{ env.ARM_UBL_ACTIVATION_CODE }}"

      - uses: ammaraskar/gcc-problem-matcher@master

      - name: Run LIT
        working-directory: ./CMSIS/Core/Test
        run: |
          ./build.py lit

      - name: Archive Test Results
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: lit-test-results
          path: ./CMSIS/Core/Test/*.xunit

      - name: Publish Test Results
        if: ${{ !cancelled() }}
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          report_individual_runs: true
          files: ./CMSIS/Core/Test/*.xunit
