name: Core Checks
on:
  workflow_dispatch:
  pull_request:
    paths: 
      - .github/workflows/core.yml
      - CMSIS/Core/Include/**/*
      - CMSIS/Core/Source/**/*
      - CMSIS/Core/Test/**/*
  push:
    branches: [main]
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lit:
    runs-on: ubuntu-22.04

    env:
      ARM_UBL_ACTIVATION_CODE: ${{ secrets.ARM_UBL_ACTIVATION_CODE }}
      CLANG_TI_VERSION: "5.0.0.STS"
      CLANG_TI_INSTALL_PATH: "~/"
      CLANG_TI_SHA256: "7a71570703f93f3682258b95d5a14a620cd6a5fc74dc5233f2d6c56d366c6da2"

    steps:
      - uses: actions/checkout@v6
      
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'    
          cache: 'pip'

      - name: Python requirements
        run: |
          pip install -r ./CMSIS/Core/Test/requirements.txt

      - name: Install LLVM dependencies and tools
        working-directory: /home/runner
        run: |
          sudo apt-get update
          sudo apt-get install libtinfo5 llvm-15-tools
          sudo ln -s /usr/bin/FileCheck-15 /usr/bin/FileCheck
    
      - name: Activate vcpkg environment
        uses: ARM-software/cmsis-actions/vcpkg@v1
        with:
          config: ./CMSIS/Core/Test/vcpkg-configuration.json
          
      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1
        with:
          code: "${{ env.ARM_UBL_ACTIVATION_CODE }}"

      - uses: ammaraskar/gcc-problem-matcher@master

      - name: Set TI ARM CLANG Environment Variables and Path
        run: |
          echo "CLANG_TI_PATH=${{ env.CLANG_TI_INSTALL_PATH }}ti-cgt-armllvm_${{ env.CLANG_TI_VERSION }}" >> $GITHUB_ENV
          echo "CLANG_TI_BIN=${{ env.CLANG_TI_INSTALL_PATH }}ti-cgt-armllvm_${{ env.CLANG_TI_VERSION }}/bin" >> $GITHUB_ENV
          echo "CLANG_TI_TOOLCHAIN_${{ env.CLANG_TI_VERSION }}=${{ env.CLANG_TI_INSTALL_PATH }}ti-cgt-armllvm_${{ env.CLANG_TI_VERSION }}/bin" >> $GITHUB_ENV
          echo "${{ env.CLANG_TI_INSTALL_PATH }}ti-cgt-armllvm_${{ env.CLANG_TI_VERSION }}/bin" >> $GITHUB_PATH

      - name: Cache TI ARM CLANG
        id: cache-ti-arm-clang
        uses: actions/cache@v4
        with:
          path: ${{ env.CLANG_TI_PATH }}
          key: ${{ runner.os }}-ti-arm-clang-${{ env.CLANG_TI_VERSION }}

      - name: Download and Verify TI ARM CLANG Installer
        if: steps.cache-ti-arm-clang.outputs.cache-hit != 'true'
        run: |
          FILE="ti_cgt_armllvm_${{ env.CLANG_TI_VERSION }}_linux-x64_installer.bin"
          URL="https://dr-download.ti.com/software-development/ide-configuration-compiler-or-debugger/MD-ayxs93eZNN/${{ env.CLANG_TI_VERSION }}/${FILE}"
    
          curl -L "$URL" -o "$FILE"
          echo "${{ env.CLANG_TI_SHA256 }}  $FILE" | sha256sum --check
          chmod +x "$FILE"
          ./"$FILE" --mode unattended --prefix "${{ env.CLANG_TI_INSTALL_PATH }}"

      - name: Print TI Arm Clang Environment
        working-directory: ./CMSIS/Core/Test
        run: |
          ls -l ~/ti-cgt-armllvm_5.0.0.STS/bin
          echo "GITHUB_PATH:"
          cat "$GITHUB_PATH"
          echo "GITHUB_ENV:"
          cat "$GITHUB_ENV"
          tiarmclang --version

      - name: Run LIT
        working-directory: ./CMSIS/Core/Test
        run: |
          ./build.py lit

      - name: Publish Test Results
        if: ${{ !cancelled() }}
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          report_individual_runs: true
          files: ./CMSIS/Core/Test/*.xunit
